### ISSUE TITLE
[1.16]Configs seem to just reset themselves to default

### ISSUE THREAD

**Issue by merlerm** [Vazkii/AkashicTome#58]
I was trying to set up the Tome for a new 1.16 pack, but every time I try to change the configs to add some custom items in the tome and launch the game, midway through loading the config file just switches back to the original default one. The same seems to happen for Morph-o-tool too, but I thought I'd only report it here for now.

I'm using akashic tome 1.4-14 and morph-o-tool 1.4-25

**Comment by merlerm** [comment]
Actually, seems to be a duplicate of https://github.com/Vazkii/AkashicTome/issues/52, so my bad on that, I completely glanced over it. I'll leave the issue open to let you know the issue persists in 1.16

**Comment by Hubry** [comment]
The config definition in [here](https://github.com/Vazkii/AkashicTome/blob/master/src/main/java/vazkii/akashictome/ConfigHandler.java#L28-L43) should be using `defineList` instead of `define`, the default validator checks object class compatibility, but  `java.util.ArrayList` cannot be cast to `java.util.Arrays$ArrayList`. This will require providing a validator for the strings so that invalid values will be rejected, though.
