### ISSUE TITLE
1.18.1 v1.5-17 Cannot add Patchouli:guide_book items

### ISSUE THREAD

**Issue by aerialspring** [Vazkii/AkashicTome#84]
Addded the itemIDs to whitelist and they still do not go into the book in the crafting table. Also added tag names to the name whitelist, but no luck. It is only the Patchouli books that won't go in.

"Allow all items to be added" = false
"Whitelisted Items" = ["roots:runedtablet", "opencomputers:tool:4", "immersiveengineering:tool:3", "integrateddynamics:on_the_dynamics_of_integration", "theoneprobe:probenote", "evilcraft:origins_of_darkness", "draconicevolution:info_tablet", "charset:tablet", "antiqueatlas:antique_atlas", **"occultism:dictionary_of_spirits", "apotheosis:apoth_chronicle", "storagenetwork:network_book", "engineersdecor:engineersdecor_manual", "productivebees:guide", "naturesaura:book", "croptopia:guide", "cyclic:cyclic_guide_book", "patchouli:guide_book"**]
"Whitelisted Names" = ["book", "tome", "lexicon", "nomicon", "manual", "knowledge", "pedia", "compendium", "guide", "codex", "journal", **"tablet", "guidebook"**]
"Blacklisted Mods" = []
"Mod Aliases" = ["nautralpledge=botania", "thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "redstonearsenal=thermalfoundation", "rftoolsdim=rftools", "rftoolspower=rftools", "rftoolscontrol=rftools", "ae2stuff=appliedenergistics2", "animus=bloodmagic", "integrateddynamics=integratedtunnels", "mekanismgenerators=mekanism", "mekanismtools=mekanism", "deepresonance=rftools", "xnet=rftools", "buildcrafttransport=buildcraft", "buildcraftfactory=buildcraft", "buildcraftsilicon=buildcraft"]

**Comment by Slickson77** [comment]
The apothesosis book went in for me with no config changes.  Can't switch to any of the books I added but that is another issue.

**Comment by C0rn3j** [comment]
Mystical Agriculture (patchouli) does go in for me but the mod doesn't work anyway due to #83 

But I cannot add Tconstruct's Materials and You.

```php
forge-1.18.1-39.0.75
AkashicTome-1.5-17
```

**Comment by Thunder-Nova** [comment]
In all the mods 7 version .41 I made a broad lists of books to add, did as well put them into the whitelist config but it got reset for some reason. 

When editing the config, I also did go and clean it for you which is provided bellow. It's easier to see each book added when placed in another line, instead of staying in the same line.

[akashictome-common.toml](https://cdn.discordapp.com/attachments/838222577343922196/941442058575573042/akashictome-common.toml)

collective books added to the file
> "occultism:dictionary_of_spirits",
> "rootsclassic:runic_tablet",
> "tconstruct:guides",
> "patchouli:guide_book",
> "alexmobs:animal_dictionary"

most books belongs to patchouli, and tinker has multiple books and each have a collective tag. Which from what I see in the mod, it just needs the collective tag which supposed to work.

Plus #83 tome is broken in that matter as well.

**Comment by ZEROX7** [comment]
so i got that issue now in version 18 ass well, it seems it allows only one book from each mod wich makes it not work for any second patchouli books you want to add you can add eather one first but not both..... maybe add a exception config for mods to with more that one guide book?
